name: fit_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.0
  csv: ^6.0.0
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  uuid: ^4.4.2
  fl_chart: ^0.69.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_fonts: ^6.3.3
  image_picker: ^1.1.2
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  table_calendar: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
